ALTER TABLE CLIENTES 
ADD CONSTRAINT UNIQUE (dni_cliente);

CREATE TABLE FACTURAS (
    nro_fc INT AUTO_INCREMENT PRIMARY KEY,
    tipo_fc ENUM('FACT A', 'FACT B', 'FACT C') NOT NULL,
    cod_cliente INT NOT NULL,
    FOREIGN KEY (cod_cliente) REFERENCES CLIENTES(cod_cliente));

ALTER TABLE TELEFONOS 
MODIFY COLUMN tipo_tel ENUM('CASA', 'MOVIL', 'TRABAJO') NOT NULL;

CREATE TABLE PRODUCTOS (
    id_producto INT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    precio DECIMAL(10,2) DEFAULT 0 NULL);
