nombre=input ()
vencimiento=input()
precio=input()
ingredientes=input()
empresa=input()
direccion=input()
telefono=input()
print("*"*4,"PANIFICADORA",empresa,"*"*4)
print("domicilio:",telefono)
print("*"*35)
print(nombre)
print(ingredientes)
print("vto:",vencimiento)
print("$",precio)